// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc5fZVRYHorlVkMJ-pGT7IyDasds2vcSo',
    appId: '1:983590018492:web:5fb923c3192698fd019fb9',
    messagingSenderId: '983590018492',
    projectId: 'proyecto-primera-pagina',
    authDomain: 'proyecto-primera-pagina.firebaseapp.com',
    storageBucket: 'proyecto-primera-pagina.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq4LLSF9FlvZiaX86ssCEGbh01g4GiPL0',
    appId: '1:983590018492:android:e73d94d5cd41693c019fb9',
    messagingSenderId: '983590018492',
    projectId: 'proyecto-primera-pagina',
    storageBucket: 'proyecto-primera-pagina.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1dcVicPzvmNTQuAgnSYiDPdnS4M_8jlw',
    appId: '1:983590018492:ios:b947a1c1ec763052019fb9',
    messagingSenderId: '983590018492',
    projectId: 'proyecto-primera-pagina',
    storageBucket: 'proyecto-primera-pagina.appspot.com',
    iosClientId: '983590018492-5lq39ud5jr6pm6cmpgc9ui6pj803qj1l.apps.googleusercontent.com',
    iosBundleId: 'com.mercadofresco.mercadoFresco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1dcVicPzvmNTQuAgnSYiDPdnS4M_8jlw',
    appId: '1:983590018492:ios:c797ecef0b791e4f019fb9',
    messagingSenderId: '983590018492',
    projectId: 'proyecto-primera-pagina',
    storageBucket: 'proyecto-primera-pagina.appspot.com',
    iosClientId: '983590018492-m1csqbmgivconrfddhh7iemb0bjkhdqc.apps.googleusercontent.com',
    iosBundleId: 'com.mercadofresco.mercadoFresco.RunnerTests',
  );
}
